services:
  postgres:
    image: postgres:16
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: kitchen_sync
      POSTGRES_PASSWORD: kitchen_sync
      POSTGRES_DB: kitchen_sync
    volumes:
      - kitchen-sync-pg:/var/lib/postgresql/data

volumes:
  kitchen-sync-pg:
