/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ApiPullRouteImport } from './routes/api/pull'
import { Route as ApiPushRouteImport } from './routes/api/push'
import { Route as ApiPullStreamRouteImport } from './routes/api/pull/stream'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPullRoute = ApiPullRouteImport.update({
  id: '/api/pull',
  path: '/api/pull',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPushRoute = ApiPushRouteImport.update({
  id: '/api/push',
  path: '/api/push',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPullStreamRoute = ApiPullStreamRouteImport.update({
  id: '/stream',
  path: '/stream',
  getParentRoute: () => ApiPullRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api/pull': typeof ApiPullRouteWithChildren
  '/api/push': typeof ApiPushRoute
  '/api/pull/stream': typeof ApiPullStreamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api/pull': typeof ApiPullRouteWithChildren
  '/api/push': typeof ApiPushRoute
  '/api/pull/stream': typeof ApiPullStreamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api/pull': typeof ApiPullRouteWithChildren
  '/api/push': typeof ApiPushRoute
  '/api/pull/stream': typeof ApiPullStreamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/api/pull' | '/api/push' | '/api/pull/stream'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/api/pull' | '/api/push' | '/api/pull/stream'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/api/pull'
    | '/api/push'
    | '/api/pull/stream'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ApiPullRoute: typeof ApiPullRouteWithChildren
  ApiPushRoute: typeof ApiPushRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pull': {
      id: '/api/pull'
      path: '/api/pull'
      fullPath: '/api/pull'
      preLoaderRoute: typeof ApiPullRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/push': {
      id: '/api/push'
      path: '/api/push'
      fullPath: '/api/push'
      preLoaderRoute: typeof ApiPushRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pull/stream': {
      id: '/api/pull/stream'
      path: '/stream'
      fullPath: '/api/pull/stream'
      preLoaderRoute: typeof ApiPullStreamRouteImport
      parentRoute: typeof ApiPullRoute
    }
  }
}

interface ApiPullRouteChildren {
  ApiPullStreamRoute: typeof ApiPullStreamRoute
}

const ApiPullRouteChildren: ApiPullRouteChildren = {
  ApiPullStreamRoute: ApiPullStreamRoute,
}

const ApiPullRouteWithChildren =
  ApiPullRoute._addFileChildren(ApiPullRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ApiPullRoute: ApiPullRouteWithChildren,
  ApiPushRoute: ApiPushRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
